-- MySQL Script generated by MySQL Workbench
-- Wed Apr 14 18:16:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aplicacion_de_votaciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aplicacion_de_votaciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aplicacion_de_votaciones` DEFAULT CHARACTER SET utf8 ;
USE `aplicacion_de_votaciones` ;

-- -----------------------------------------------------
-- Table `aplicacion_de_votaciones`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aplicacion_de_votaciones`.`Roles` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `Rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `Roles_UNIQUE` (`Rol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aplicacion_de_votaciones`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aplicacion_de_votaciones`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Apellido` VARCHAR(255) NOT NULL,
  `Usuario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aplicacion_de_votaciones`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aplicacion_de_votaciones`.`Eventos` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `Evento` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aplicacion_de_votaciones`.`Roles_X_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aplicacion_de_votaciones`.`Roles_X_Usuario` (
  `idRol x Usuario` INT NOT NULL AUTO_INCREMENT,
  `Roles_idRol` INT NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idRol x Usuario`),
  INDEX `fk_Roles_X_Usuario_Roles_idx` (`Roles_idRol` ASC) VISIBLE,
  INDEX `fk_Roles_X_Usuario_Usuarios1_idx` (`Usuarios_idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `ux_idRol_idUsuario` (`Roles_idRol` ASC, `Usuarios_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Roles_X_Usuario_Roles`
    FOREIGN KEY (`Roles_idRol`)
    REFERENCES `aplicacion_de_votaciones`.`Roles` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Roles_X_Usuario_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `aplicacion_de_votaciones`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aplicacion_de_votaciones`.`Nominados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aplicacion_de_votaciones`.`Nominados` (
  `idNominado` INT NOT NULL AUTO_INCREMENT,
  `Nominado` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idNominado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aplicacion_de_votaciones`.`Nominados_X_Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aplicacion_de_votaciones`.`Nominados_X_Evento` (
  `idNominado_X_Evento` INT NOT NULL AUTO_INCREMENT,
  `Nominados_idNominado` INT NOT NULL,
  `Eventos_idEvento` INT NOT NULL,
  PRIMARY KEY (`idNominado_X_Evento`),
  INDEX `fk_Nominados_X_Evento_Nominados1_idx` (`Nominados_idNominado` ASC) VISIBLE,
  INDEX `fk_Nominados_X_Evento_Eventos1_idx` (`Eventos_idEvento` ASC) VISIBLE,
  UNIQUE INDEX `ux_idNominado_idEvento` (`Nominados_idNominado` ASC, `Eventos_idEvento` ASC) VISIBLE,
  CONSTRAINT `fk_Nominados_X_Evento_Nominados1`
    FOREIGN KEY (`Nominados_idNominado`)
    REFERENCES `aplicacion_de_votaciones`.`Nominados` (`idNominado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nominados_X_Evento_Eventos1`
    FOREIGN KEY (`Eventos_idEvento`)
    REFERENCES `aplicacion_de_votaciones`.`Eventos` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aplicacion_de_votaciones`.`Votos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aplicacion_de_votaciones`.`Votos` (
  `idVoto` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuario` INT NOT NULL,
  `Nominado_X_Evento_idNominado_X_Evento` INT NOT NULL,
  PRIMARY KEY (`idVoto`),
  INDEX `fk_Votos_Usuarios1_idx` (`Usuarios_idUsuario` ASC) VISIBLE,
  INDEX `fk_Votos_Nominados_X_Evento1_idx` (`Nominado_X_Evento_idNominado_X_Evento` ASC) VISIBLE,
  CONSTRAINT `fk_Votos_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `aplicacion_de_votaciones`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Votos_Nominados_X_Evento1`
    FOREIGN KEY (`Nominado_X_Evento_idNominado_X_Evento`)
    REFERENCES `aplicacion_de_votaciones`.`Nominados_X_Evento` (`idNominado_X_Evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
