-- MySQL Script generated by MySQL Workbench
-- Wed Apr 14 17:43:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `Roles` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRoles`),
  UNIQUE INDEX `Roles_UNIQUE` (`Roles` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Eventos` (
  `idEventos` INT NOT NULL AUTO_INCREMENT,
  `Evento` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEventos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles_X_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles_X_Usuario` (
  `idRoles x Usuario` INT NOT NULL AUTO_INCREMENT,
  `Roles_idRoles` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idRoles x Usuario`),
  INDEX `fk_Roles_X_Usuario_Roles_idx` (`Roles_idRoles` ASC) VISIBLE,
  INDEX `fk_Roles_X_Usuario_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Roles_X_Usuario_Roles`
    FOREIGN KEY (`Roles_idRoles`)
    REFERENCES `mydb`.`Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Roles_X_Usuario_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nominados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nominados` (
  `idNominados` INT NOT NULL AUTO_INCREMENT,
  `Nominados` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idNominados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nominados_X_Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nominados_X_Evento` (
  `idNominados_X_Evento` INT NOT NULL AUTO_INCREMENT,
  `Nominados_idNominados` INT NOT NULL,
  `Eventos_idEventos` INT NOT NULL,
  PRIMARY KEY (`idNominados_X_Evento`),
  INDEX `fk_Nominados_X_Evento_Nominados1_idx` (`Nominados_idNominados` ASC) VISIBLE,
  INDEX `fk_Nominados_X_Evento_Eventos1_idx` (`Eventos_idEventos` ASC) VISIBLE,
  CONSTRAINT `fk_Nominados_X_Evento_Nominados1`
    FOREIGN KEY (`Nominados_idNominados`)
    REFERENCES `mydb`.`Nominados` (`idNominados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nominados_X_Evento_Eventos1`
    FOREIGN KEY (`Eventos_idEventos`)
    REFERENCES `mydb`.`Eventos` (`idEventos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Votos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Votos` (
  `idVotos` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Nominados_X_Evento_idNominados_X_Evento` INT NOT NULL,
  PRIMARY KEY (`idVotos`),
  INDEX `fk_Votos_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  INDEX `fk_Votos_Nominados_X_Evento1_idx` (`Nominados_X_Evento_idNominados_X_Evento` ASC) VISIBLE,
  CONSTRAINT `fk_Votos_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Votos_Nominados_X_Evento1`
    FOREIGN KEY (`Nominados_X_Evento_idNominados_X_Evento`)
    REFERENCES `mydb`.`Nominados_X_Evento` (`idNominados_X_Evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
